sudo: enable
language: node_js
node_js:
  - "8"
  - "9"
cache:
  directories:
    - node_modules
script:
 - make test

after_success:
 - npm run coveralls

notifications:
  # email:
  #   recipients:
  #     - jweboy0630@gmail.com
  #   on_success: never
  #   on_failure: always
  slack: 
    rooms:
      - jweboytm:woLS6D9oasTaWyC1Ks4zqCne
    on_success: change
    on_failure: always
    on_pull_requests: false